import Foundation

/// Individually authored decisions; paragraph review is recorded in docs/ContentReview.md.
enum OSHAExpansion {
    struct Decision {
        let id: String
        let section: String
        let paragraph: String
        let prompt: String
        let answers: [String] // First is correct; quiz/session UI shuffles choices.
        let explanation: String
        var question: QuizQuestion {
            QuizQuestion(id: id, tracks: id == "fire-hot-work-q210" ? [.osha] : nil, prompt: prompt, difficulty: .medium,
                choices: answers.enumerated().map { index, answer in QuizChoice(id: "\(id)-\(["a", "b", "c", "d"][index])", text: answer, isCorrect: index == 0) })
        }
        var entry: QuestionExplanations.Entry {
            QuestionExplanations.Entry(text: explanation, reference: QuestionReference(title: "29 CFR \(section)", section: paragraph,
                url: URL(string: "https://www.ecfr.gov/current/title-29/section-\(section)#p-\(section)\(paragraph)")!))
        }
    }
    static let decisions: [Decision] = [
        Decision(id: "wws-q1", section: "1910.22", paragraph: "(d)(2)", prompt: "A damaged floor cannot be repaired until tomorrow. What interim action is required?", answers: ["Guard the hazard to prevent use until corrected", "Post a repair date and leave the route open", "Require only slower walking", "Wait for the next scheduled inspection"], explanation: "Prevent access until the hazardous condition is corrected; scheduling a repair is not an interim control."),
        Decision(id: "wws-q2", section: "1910.22", paragraph: "(d)(3)", prompt: "A repair changes a platform's structural integrity. Who must perform or supervise it?", answers: ["A qualified person", "Any employee with a work order", "Only the person who found it", "The purchasing clerk"], explanation: "Structural repairs require qualified performance or supervision, beyond ordinary housekeeping."),
        Decision(id: "wws-q3", section: "1910.23", paragraph: "(b)(9)", prompt: "A ladder was inspected yesterday and will be used on today's next shift. What is required?", answers: ["Inspect before initial use this shift and more often as needed", "Rely on yesterday's inspection", "Inspect only monthly", "Inspect only after a fall"], explanation: "Inspection is shift-based and more frequent when necessary; yesterday's check is insufficient."),
        Decision(id: "wws-q4", section: "1910.23", paragraph: "(b)(10)", prompt: "A ladder has a cracked rail. What is the appropriate disposition?", answers: ["Tag it against use and remove it from service until properly repaired or replaced", "Allow short jobs only", "Reduce the permitted load by half", "Let each employee decide"], explanation: "A visible defect requires immediate removal from service, not an improvised load reduction."),
        Decision(id: "wws-q5", section: "1910.23", paragraph: "(c)(3)", prompt: "A worker is below the ladder's load rating, but tools push the total above it. What is appropriate?", answers: ["Select a ladder that supports the worker and all carried loads", "Count the worker's body weight only", "Exclude tools carried in a belt", "Allow overload for less than five minutes"], explanation: "The intended load includes tools and materials, not just body weight."),
        Decision(id: "wws-q6", section: "1910.23", paragraph: "(c)(8)", prompt: "A task is reachable only from a stepladder's top step. What should the supervisor do?", answers: ["Provide suitable access equipment instead of using the cap or top step", "Allow the top step with a spotter", "Allow the cap if dry", "Brace the ladder and permit either step"], explanation: "The cap and top step are not standing steps; choose appropriate access equipment."),
        Decision(id: "wws-q7", section: "1910.23", paragraph: "(c)(11)", prompt: "A portable ladder provides access to an upper landing. What rail extension is required?", answers: ["At least 3 feet above the landing", "Flush with the landing", "One rung above the landing", "Exactly 6 inches above the landing"], explanation: "The side rails must extend at least three feet for this access arrangement."),
        Decision(id: "wws-q8", section: "1910.23", paragraph: "(b)(13)", prompt: "A bulky package could unbalance a worker climbing a ladder. What is appropriate?", answers: ["Use a separate safe method to move the package", "Carry it if it is light", "Climb backward for visibility", "Hold it with both hands"], explanation: "Do not climb with a load that could cause loss of balance, even if its weight is low."),
        Decision(id: "wws-q9", section: "1910.30", paragraph: "(c)(2)", prompt: "New fall protection equipment makes the prior training obsolete. What is needed?", answers: ["Retrain affected employees for the changed equipment", "Wait for an injury", "Use only the old training record", "Wait five years"], explanation: "Equipment changes that invalidate previous training trigger retraining."),
        Decision(id: "wws-q10", section: "1910.28", paragraph: "(b)(9)(i)(D)", prompt: "An existing fixed ladder extends more than 24 feet above a lower level and has only a cage. What is the final transition requirement?", answers: ["Install a personal fall arrest or ladder safety system by November 18, 2036", "A cage alone remains sufficient indefinitely", "Remove all ladders by 2030", "Apply the deadline only to portable ladders"], explanation: "The final fixed-ladder transition requires a fall arrest or ladder safety system; a cage alone does not meet it."),
        Decision(id: "ppeha-q1", section: "1910.132", paragraph: "(d)(2)", prompt: "A hazard assessment is complete but its certification lacks the workplace and assessment date. What should be corrected?", answers: ["Identify the workplace, certifier, dates, and document as a certification", "Add only a purchase order", "Add only equipment prices", "Use an unsigned generic checklist"], explanation: "Certification must identify the evaluation and who certified it; a generic checklist is insufficient."),
        Decision(id: "ppeha-q2", section: "1910.132", paragraph: "(d)(1)(iii)", prompt: "One glove model protects against the chemical but fits several employees poorly. What must change?", answers: ["Select protective equipment that properly fits each employee", "Accept the single size for purchasing consistency", "Allow loose gloves for all tasks", "Use the cheapest size"], explanation: "Protection must fit the individual; chemical resistance alone does not establish suitability."),
        Decision(id: "ppeha-q3", section: "1910.132", paragraph: "(f)(3)(i)", prompt: "A workplace change makes employees' previous PPE training obsolete. What is required?", answers: ["Retrain the affected employees", "Wait for annual budgeting", "Keep old training because it was signed", "Replace the attendance sheet only"], explanation: "Retraining follows changes that invalidate prior training, not merely a calendar cycle."),
        Decision(id: "ppeha-q4", section: "1910.132", paragraph: "(f)(3)(ii)", prompt: "New PPE operates differently from the equipment used in prior training. What should happen?", answers: ["Retrain affected employees when that change makes earlier training obsolete", "Use the old instructions unchanged", "Train only new hires", "Require employees to learn by trial"], explanation: "A change in PPE can invalidate earlier training and require retraining."),
        Decision(id: "ppeha-q5", section: "1910.132", paragraph: "(f)(3)(iii)", prompt: "An experienced worker repeatedly misuses assigned PPE after training. What is the correct response?", answers: ["Retrain to restore the required understanding and skill", "Treat the old certificate as conclusive", "Wait until equipment replacement", "Remove all PPE requirements"], explanation: "Observed knowledge or use deficiencies can trigger retraining despite prior attendance."),
        Decision(id: "ppeha-q6", section: "1910.132", paragraph: "(h)(2)", prompt: "Non-specialty prescription safety glasses may be worn off the job site. Which payment rule applies?", answers: ["The employer need not pay under this specific exception", "The employer must always pay for all prescription glasses", "Employees must pay for every type of eye protection", "The exception applies only to disposable goggles"], explanation: "This narrow exception depends on non-specialty equipment and permission for off-site use."),
        Decision(id: "ppeha-q7", section: "1910.132", paragraph: "(h)(4)(iii)", prompt: "An ordinary raincoat is used solely for weather protection. Which payment rule applies?", answers: ["The employer is not required to pay under this exception", "All weather clothing is always employer-paid", "All chemical protective coats are also exempt", "The employee must buy every protective garment"], explanation: "Ordinary weather gear has a payment exception; chemical protective clothing is a different situation."),
        Decision(id: "ppeha-q8", section: "1910.132", paragraph: "(h)(5)", prompt: "Required employer-paid gloves wear out in normal use. Who pays for replacement?", answers: ["The employer; the loss or intentional-damage exception does not apply", "The employee after the first pair", "Split the cost automatically", "Charge the employee unless injured"], explanation: "Normal wear is not loss or intentional damage; required replacement remains employer-paid."),
        Decision(id: "ppeha-q9", section: "1910.132", paragraph: "(h)(6)", prompt: "A worker offers adequate personally owned PPE, outside the payment exceptions. Which arrangement is allowed?", answers: ["Voluntary use without reimbursement, but the employer cannot require self-purchase", "Require everyone to buy the same equipment", "Deduct the cost from all employees", "Reject any employee-owned equipment categorically"], explanation: "Voluntary use can be allowed; it cannot become mandatory employee payment outside the exceptions."),
        Decision(id: "ppeha-q10", section: "1910.133", paragraph: "(a)(3)", prompt: "An employee needs prescription lenses and impact protection. What is acceptable?", answers: ["Protective prescription eyewear or suitable protection over lenses without disturbing either position", "Ordinary prescription glasses alone", "A face shield regardless of eye protection", "Removing prescription lenses whenever working"], explanation: "Corrective lenses do not remove the need for suitable protection and compatible fit."),
        Decision(id: "rk-q1", section: "1904.1", paragraph: "(a)(1)", prompt: "An employer had ten or fewer employees throughout the previous calendar year. What is the usual recordkeeping position?", answers: ["Partially exempt from routine records unless notified otherwise, but severe-event reporting still applies", "Exempt from all OSHA requirements", "Required to file a daily injury log regardless", "Exempt only if there were no injuries"], explanation: "The small-employer exemption concerns routine records; it does not eliminate severe-event reporting."),
        Decision(id: "rk-q2", section: "1904.29", paragraph: "(b)(3)", prompt: "A covered employer learns that an injury is recordable. When must it enter the case and complete the incident report?", answers: ["Within seven calendar days of receiving the information", "Within seven business days", "At the end of the quarter", "Only after final medical discharge"], explanation: "The recording window uses calendar days and starts when recordability information is received."),
        Decision(id: "rk-q3", section: "1904.29", paragraph: "(b)(4)", prompt: "A covered employer wants to use an equivalent incident form. What must it provide?", answers: ["The same information, readability, understandability, and completion instructions as the OSHA form", "Only the total injury count", "Any insurer form regardless of missing fields", "Only the employee's name and date"], explanation: "Equivalent forms must preserve the required information and usability, not just their title."),
        Decision(id: "rk-q4", section: "1904.29", paragraph: "(b)(7)(iv)", prompt: "A recordable case involves HIV infection. How is it treated on the injury log?", answers: ["As a privacy concern case", "As public employee-name information in every copy", "Never recorded", "Recorded only if the employee requests it"], explanation: "HIV infection is a listed privacy concern; privacy treatment does not remove recordability."),
        Decision(id: "rk-q5", section: "1904.32", paragraph: "(b)(3)", prompt: "The annual summary is ready. What must certification establish?", answers: ["A company executive reasonably believes it is correct and complete after the required review", "Only that payroll totals match", "Only that no employees complained", "Only that the form was printed"], explanation: "Certification includes examination of the log and reasonable belief in completeness and accuracy."),
        Decision(id: "rk-q6", section: "1904.32", paragraph: "(b)(4)(iii)", prompt: "Which person qualifies as a company executive to certify a covered establishment's summary?", answers: ["The highest-ranking company official working at that establishment", "Any employee assigned data entry", "Any outside vendor", "Only the newest supervisor"], explanation: "The rule lists qualifying executive roles, including this establishment official."),
        Decision(id: "rk-q7", section: "1904.32", paragraph: "(b)(6)", prompt: "A covered establishment has completed its annual summary. What posting period applies to the year covered by the records?", answers: ["February 1 through April 30 of the year following the year covered", "January 1 through January 31 only", "Only on request", "March 2 for one day"], explanation: "The summary remains posted for the full February-through-April period."),
        Decision(id: "rk-q8", section: "1904.39", paragraph: "(a)(1)", prompt: "A work-related incident causes an employee's immediate death and the employer learns immediately. What is the OSHA reporting window?", answers: ["Within eight hours", "Within twenty-four hours", "Within seven calendar days", "Only at annual summary time"], explanation: "The fatality reporting window is eight hours in these stated circumstances, separate from routine recording."),
        Decision(id: "rk-q9", section: "1904.39", paragraph: "(a)(2)", prompt: "A work-related amputation occurs immediately and the employer learns immediately. What is the OSHA reporting window?", answers: ["Within twenty-four hours", "Within seven calendar days", "Within thirty days", "Only if three employees are injured"], explanation: "A single qualifying amputation triggers severe-event reporting within twenty-four hours."),
        Decision(id: "rk-q10", section: "1904.39", paragraph: "(b)(10)", prompt: "A worker is formally admitted only for observation and diagnostic testing after an incident. Is that hospitalization itself reportable under this rule?", answers: ["No, observation or diagnostic testing alone is excluded", "Yes, every hospital visit is reportable", "Only if an ambulance was used", "Only if the employer has over one hundred employees"], explanation: "The inpatient-reporting definition requires care or treatment; other reportable outcomes must still be evaluated separately."),
        Decision(id: "eap-q1", section: "1910.38", paragraph: "(c)(1)", prompt: "A required emergency action plan lists exits but omits how to report an emergency. What should be added?", answers: ["Procedures for reporting a fire or other emergency", "Only an insurance contact", "Only the annual inspection schedule", "Only a list of extinguishers"], explanation: "Reporting procedures are a required element in addition to evacuation routes."),
        Decision(id: "eap-q2", section: "1910.38", paragraph: "(c)(2)", prompt: "A required plan says only 'leave quickly.' What is missing?", answers: ["Evacuation procedures, including type and route assignments", "A promise that no drills will occur", "A list of employee salaries", "A universal instruction to use elevators"], explanation: "The plan needs actionable evacuation procedures, not just a general instruction."),
        Decision(id: "eap-q3", section: "1910.38", paragraph: "(c)(3)", prompt: "Designated employees must briefly operate critical plant systems before evacuation. What must the plan cover?", answers: ["Their procedures before they evacuate", "Permission to remain indefinitely", "Only the general exit map", "Instructions for all employees to stay"], explanation: "Critical-operation duties need defined procedures before evacuation; the rule does not authorize indefinite exposure."),
        Decision(id: "eap-q4", section: "1910.38", paragraph: "(c)(4)", prompt: "Everyone reaches the assembly point, but no method identifies missing employees. What plan element is absent?", answers: ["Procedures to account for all employees after evacuation", "A rule to ignore missing people", "Only a parking diagram", "A requirement to reenter for belongings"], explanation: "Accounting procedures help identify missing people without improvising reentry."),
        Decision(id: "eap-q5", section: "1910.38", paragraph: "(c)(5)", prompt: "Some employees have assigned medical or rescue duties. What must the plan include?", answers: ["Procedures for those assigned duties", "An assumption that all employees perform rescue", "Only a first-aid kit inventory", "Instructions to enter any hazardous area immediately"], explanation: "Assigned rescue or medical duties need procedures; a plan is not universal rescue qualification."),
        Decision(id: "eap-q6", section: "1910.38", paragraph: "(f)(2)", prompt: "An employee's responsibilities under the plan change. What must the employer do?", answers: ["Review the plan with that employee", "Wait until the next injury", "Review only when the employee asks", "Replace the employee's badge only"], explanation: "Changed responsibilities trigger review with the affected employee."),
        Decision(id: "eap-q7", section: "1910.38", paragraph: "(f)(3)", prompt: "A covered emergency action plan changes its evacuation procedures. What is required?", answers: ["Review the changed plan with covered employees", "Keep the old briefing indefinitely", "Notify only visitors", "Wait until an actual emergency"], explanation: "A changed plan triggers review; old instructions may no longer be usable."),
        Decision(id: "eap-q8", section: "1910.39", paragraph: "(c)(1)", prompt: "A required fire prevention plan identifies materials but ignores ignition sources. What is missing?", answers: ["Potential ignition sources, their controls, and protection for major hazards", "Only evacuation attendance", "Only the cleaning contractor's phone", "Only building replacement cost"], explanation: "The plan links major fire hazards to handling, ignition controls, and appropriate protection."),
        Decision(id: "eap-q9", section: "1910.39", paragraph: "(c)(2)", prompt: "Combustible waste builds up near work areas. What must the required fire prevention plan address?", answers: ["Procedures controlling accumulations of flammable and combustible waste", "Only a yearly photograph", "Permission to store waste indefinitely", "Only sprinkler inspection dates"], explanation: "Waste accumulation controls are a distinct required plan element."),
        Decision(id: "eap-q10", section: "1910.39", paragraph: "(c)(3)", prompt: "Heat-producing equipment has safeguards against igniting nearby material. What must the plan include?", answers: ["Procedures for regular maintenance of those safeguards", "Only the original purchase date", "Only an instruction to repair after fire", "A waiver from all maintenance"], explanation: "The plan must address maintenance that preserves the safeguards' preventive function."),
        Decision(id: "resp-q1", section: "1910.134", paragraph: "(c)(1)", prompt: "Respirators are required at a workplace. What program is needed?", answers: ["A written program with worksite-specific procedures, updated as conditions change", "Only a receipt for respirators", "Only a generic poster", "An oral program regardless of conditions"], explanation: "Required use needs a written, site-specific program rather than purchasing alone."),
        Decision(id: "resp-q2", section: "1910.134", paragraph: "(c)(2)(i)", prompt: "The employer permits voluntary respirator use after determining it creates no hazard. What information must users receive?", answers: ["The standard's Appendix D information", "Only a purchase receipt", "Only exposure limits", "No information because use is voluntary"], explanation: "Voluntary users must receive Appendix D information even when respirator use is not required."),
        Decision(id: "resp-q3", section: "1910.134", paragraph: "(c)(2)(ii)", prompt: "An employee voluntarily uses an elastomeric respirator. What additional program elements are needed?", answers: ["Medical ability and safe cleaning, storage, and maintenance; the filtering-facepiece exception does not cover it", "No program elements for any voluntary use", "Only annual purchasing review", "Only the filtering-facepiece exception"], explanation: "Voluntary elastomeric use needs the necessary medical and maintenance elements; filtering facepieces have a narrower exception."),
        Decision(id: "resp-q4", section: "1910.134", paragraph: "(c)(3)", prompt: "Who should administer a complex respiratory protection program?", answers: ["A person qualified by training or experience appropriate to its complexity", "Whoever orders supplies regardless of qualifications", "Any employee selected at random", "Only the newest respirator user"], explanation: "Administrator qualifications must match the program, rather than a job title alone."),
        Decision(id: "resp-q5", section: "1910.134", paragraph: "(d)(1)(ii)", prompt: "A supplier offers an unapproved combination of parts from certified respirators. What should the employer require?", answers: ["A NIOSH-certified respirator used within its certification conditions", "Any combination if parts individually fit", "Any device labeled comfortable", "Only a low purchase price"], explanation: "Certification applies to the approved configuration and its conditions of use."),
        Decision(id: "resp-q6", section: "1910.134", paragraph: "(g)(1)(i)(A)", prompt: "Facial hair crosses the sealing surface of a tight-fitting respirator. What is required?", answers: ["Do not permit that tight-fitting use while the hair interferes with the seal or valve function", "Tighten straps and proceed", "Accept a past fit test as sufficient", "Skip the seal check"], explanation: "Hair at the sealing surface or affecting valves prevents permitted tight-fitting use."),
        Decision(id: "resp-q7", section: "1910.134", paragraph: "(g)(1)(iii)", prompt: "A worker passed a fit test last month and dons the respirator today. What is still required?", answers: ["A user seal check each time it is put on", "No checks until next year's fit test", "Only checking cartridge color", "Only checking the training roster"], explanation: "A seal check on each donning is separate from the fit test."),
        Decision(id: "resp-q8", section: "1910.134", paragraph: "(h)(1)(ii)", prompt: "A respirator is shared between employees. When must it be cleaned and disinfected?", answers: ["Before being worn by a different individual", "Only at the end of each year", "Only if visibly broken", "Only after an exposure incident"], explanation: "Shared equipment must be cleaned and disinfected before another person wears it."),
        Decision(id: "resp-q9", section: "1910.134", paragraph: "(h)(2)(i)", prompt: "A respirator is left where sunlight, dust, and chemicals can damage it. What should change?", answers: ["Store it protected from damage and contamination, preventing facepiece or valve deformation", "Store it beside the chemical source", "Compress it under heavy tools", "Rely on the next fit test"], explanation: "Storage must protect the equipment and preserve its shape, not merely keep it nearby."),
        Decision(id: "resp-q10", section: "1910.134", paragraph: "(m)(2)(ii)", prompt: "A new fit test has just been completed. How long must its record be retained?", answers: ["Until the next fit test is administered", "Only until the next work shift", "Exactly seven calendar days", "Only while the test equipment is rented"], explanation: "Retain the current fit-test record until the next test replaces it."),
        Decision(id: "fire-hot-work-q210", section: "1910.252", paragraph: "(a)(2)(vi)(B)", prompt: "Welding is requested in a sprinklered building while its sprinkler protection is impaired. What is the appropriate decision?", answers: ["Do not perform the hot work in that condition", "Proceed with a longer fire watch only", "Proceed if work lasts under thirty minutes", "Proceed if a supervisor signs a waiver"], explanation: "Hot work is prohibited in sprinklered buildings while that protection is impaired; a fire watch does not remove the prohibition."),
    ]
    static let entries = Dictionary(uniqueKeysWithValues: decisions.map { ($0.id, $0.entry) })
    static let hotWorkQuestion = decisions.last!.question
    static let moduleIDs: Set<String> = ["wws", "ppeha", "rk", "eap", "resp"]
    static let modules: [TrainingModule] = [
        make("wws", "Walking-Working Surfaces", "Inspect surfaces, ladders, and fall protection training"),
        make("ppeha", "PPE Hazard Assessment", "Document decisions, fit, retraining, and payment exceptions"),
        make("rk", "Recordkeeping", "Apply injury records, privacy, and severe-event reporting"),
        make("eap", "Emergency Action & Fire Prevention", "Prepare evacuation and fire prevention procedures"),
        make("resp", "Respiratory Protection", "Manage programs, use, maintenance, and records")
    ]
    private static func foundation(_ id: String) -> LessonPage {
        let bullets: [String]
        switch id {
        case "wws": bullets = [
            "Keep surfaces free of hazards, inspect regularly and as necessary, and support the maximum intended load. Correct hazards before reuse, guard access when correction is delayed, and use a qualified person for structural repair. (29 CFR 1910.22(a)(3), (b), (d))",
            "For ordinary ladders, rung spacing is 10–14 inches; specified exceptions apply. Inspect before first use each shift, face the ladder, grasp it with at least one hand, and avoid unbalancing loads. (29 CFR 1910.23(b)(2), (9)–(13))",
            "Fall-hazard training is by a qualified person. Retrain when workplace or equipment changes invalidate training, or knowledge or use shows a deficiency. (29 CFR 1910.30(a)(2), (c))"
        ]
        case "ppeha": bullets = [
            "Communicate selection decisions, fit protection to each employee, and certify the assessment. Employers remain responsible for the adequacy, maintenance, and sanitation of employee-owned PPE. (29 CFR 1910.132(b), (d))",
            "Training covers when and what PPE is needed, how to wear and adjust it, limitations, and care, useful life, and disposal. Demonstrate understanding and proper use before the work. (29 CFR 1910.132(f)(1)–(2))",
            "Assessment and training paragraphs (d) and (f) apply to eye/face, head, foot, hand, and personal fall protection under .133/.135/.136/.138/.140; respiratory and electrical protective equipment have their own requirements. (29 CFR 1910.132(g))"
        ]
        case "rk": bullets = [
            "Determine work-relatedness, new-case status, and recording criteria. First aid is the defined list, not whatever a provider calls minor treatment; days-away counts use calendar days, with the specified 180-day cap. (29 CFR 1904.5, 1904.7(b)(3), (b)(5)(ii))",
            "Retain required records for five years following the covered year. Update the stored 300 Log for newly discovered recordable cases and classification or outcome changes. (29 CFR 1904.33(a), (b)(1))",
            "Reporting procedures must not deter reporting. Provide covered employee log copies by the end of the next business day and records requested by authorized government representatives within four business hours. Covered electronic submissions are due March 2. Check establishment size and industry applicability. (29 CFR 1904.35(b)(1), (b)(2)(iii), 1904.40(a), 1904.41(c))",
            "Severe-event reporting is separate from routine recording. For delayed outcomes, the reporting rule covers fatalities within 30 days of the incident and hospitalization, amputation, or eye loss within 24 hours; delayed knowledge has separate clock rules. (29 CFR 1904.39(b)(6)–(8))"
        ]
        case "eap": bullets = [
            "An emergency action or fire prevention plan is required when another applicable standard requires it. Plans are written, kept at the workplace, and available for review; employers with ten or fewer employees may communicate them orally. (29 CFR 1910.38(a)–(b), 1910.39(a)–(b))",
            "Use distinctive alarm signals and designate and train evacuation assistants. Review emergency duties on initial assignment, changed responsibilities, and plan changes. (29 CFR 1910.38(d)–(f))",
            "The fire prevention plan identifies major hazards, ignition controls, waste control, safeguard maintenance, and responsible employees for ignition equipment and fuel hazards. Explain job fire hazards at initial assignment and review the self-protection portions. (29 CFR 1910.39(c)–(d))"
        ]
        default: bullets = [
            "Evaluate the respiratory hazard and choose suitable certified equipment. IDLH selection requires a full-face pressure-demand SCBA rated for at least 30 minutes or a full-face pressure-demand supplied-air respirator with auxiliary self-contained supply, with the other required safeguards. (29 CFR 1910.134(d)(2)(i))",
            "Tight-fitting respirators require fit testing before initial use, when the facepiece changes, and at least annually. A seal check on each donning is separate. (29 CFR 1910.134(f)(2), (g)(1)(iii))",
            "Inspect routine respirators before each use and during cleaning; emergency respirators require at least monthly inspection and function checks around use. Retrain annually and sooner for relevant changes or deficiencies. (29 CFR 1910.134(h)(3)(i), (k)(5))"
        ]
        }
        return LessonPage(id: id + "-foundation", title: "Before you begin", bullets: bullets)
    }
    private static func make(_ id: String, _ title: String, _ subtitle: String) -> TrainingModule {
        let items = decisions.filter { $0.id.hasPrefix(id + "-q") }
        let pages = stride(from: 0, to: items.count, by: 2).map { offset in
            LessonPage(id: "\(id)-lesson-\(offset)", title: ["Assess the situation", "Apply the rule", "Check the exception", "Verify the controls", "Keep the evidence"][offset / 2],
                bullets: items[offset..<offset+2].map { "\($0.explanation) (29 CFR \($0.section)\($0.paragraph))" })
        }
        let steps = items.prefix(3).enumerated().map { index, item in
            ScenarioStep(id: "\(id)-step-\(index)", prompt: item.prompt, options: item.question.choices.map {
                ScenarioOption(id: $0.id, text: $0.text, feedback: item.explanation, isCorrect: $0.isCorrect, nextStepId: index < 2 ? "\(id)-step-\(index + 1)" : nil)
            })
        }
        return TrainingModule(id: id, title: title, subtitle: subtitle, estimatedMinutes: 15, difficulty: "Applied", tags: Array(Set(items.map { "29 CFR \($0.section)" })).sorted(),
            objectives: [subtitle, "Recognize conditions and exceptions", "Verify the cited paragraph before field use"], lessonPages: [foundation(id)] + pages,
            scenario: Scenario(title: "\(title): inspection decisions", intro: "Work through three decisions. Use the stated conditions and the cited standards.", startStepId: "\(id)-step-0", steps: steps), quiz: items.map(\.question))
    }
}
